//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AgencyClient.ServiceReservationHotel2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReservationHotelService2Soap", Namespace="http://tempuri.org/")]
    public partial class ReservationHotelService2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDisponibilitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveRoomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHotelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReservationHotelService2() {
            this.Url = global::AgencyClient.Properties.Settings.Default.AgencyClient_ServiceReservationHotel2_ReservationHotelService2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDisponibilitesCompletedEventHandler GetDisponibilitesCompleted;
        
        /// <remarks/>
        public event ReserveRoomeCompletedEventHandler ReserveRoomeCompleted;
        
        /// <remarks/>
        public event SendImageCompletedEventHandler SendImageCompleted;
        
        /// <remarks/>
        public event GetHotelCompletedEventHandler GetHotelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDisponibilites", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rome[] GetDisponibilites(string AgenceName, string AgencePwd, string DateDR, string DateFR, int NbPersonnes) {
            object[] results = this.Invoke("GetDisponibilites", new object[] {
                        AgenceName,
                        AgencePwd,
                        DateDR,
                        DateFR,
                        NbPersonnes});
            return ((Rome[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDisponibilitesAsync(string AgenceName, string AgencePwd, string DateDR, string DateFR, int NbPersonnes) {
            this.GetDisponibilitesAsync(AgenceName, AgencePwd, DateDR, DateFR, NbPersonnes, null);
        }
        
        /// <remarks/>
        public void GetDisponibilitesAsync(string AgenceName, string AgencePwd, string DateDR, string DateFR, int NbPersonnes, object userState) {
            if ((this.GetDisponibilitesOperationCompleted == null)) {
                this.GetDisponibilitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDisponibilitesOperationCompleted);
            }
            this.InvokeAsync("GetDisponibilites", new object[] {
                        AgenceName,
                        AgencePwd,
                        DateDR,
                        DateFR,
                        NbPersonnes}, this.GetDisponibilitesOperationCompleted, userState);
        }
        
        private void OnGetDisponibilitesOperationCompleted(object arg) {
            if ((this.GetDisponibilitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDisponibilitesCompleted(this, new GetDisponibilitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReserveRoome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rome ReserveRoome(string AgenceName, string AgencePwd, string DateDR, string DateFR, int room_id, string nom, string prenom) {
            object[] results = this.Invoke("ReserveRoome", new object[] {
                        AgenceName,
                        AgencePwd,
                        DateDR,
                        DateFR,
                        room_id,
                        nom,
                        prenom});
            return ((Rome)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveRoomeAsync(string AgenceName, string AgencePwd, string DateDR, string DateFR, int room_id, string nom, string prenom) {
            this.ReserveRoomeAsync(AgenceName, AgencePwd, DateDR, DateFR, room_id, nom, prenom, null);
        }
        
        /// <remarks/>
        public void ReserveRoomeAsync(string AgenceName, string AgencePwd, string DateDR, string DateFR, int room_id, string nom, string prenom, object userState) {
            if ((this.ReserveRoomeOperationCompleted == null)) {
                this.ReserveRoomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveRoomeOperationCompleted);
            }
            this.InvokeAsync("ReserveRoome", new object[] {
                        AgenceName,
                        AgencePwd,
                        DateDR,
                        DateFR,
                        room_id,
                        nom,
                        prenom}, this.ReserveRoomeOperationCompleted, userState);
        }
        
        private void OnReserveRoomeOperationCompleted(object arg) {
            if ((this.ReserveRoomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveRoomeCompleted(this, new ReserveRoomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendImage(int id) {
            object[] results = this.Invoke("SendImage", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendImageAsync(int id) {
            this.SendImageAsync(id, null);
        }
        
        /// <remarks/>
        public void SendImageAsync(int id, object userState) {
            if ((this.SendImageOperationCompleted == null)) {
                this.SendImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendImageOperationCompleted);
            }
            this.InvokeAsync("SendImage", new object[] {
                        id}, this.SendImageOperationCompleted, userState);
        }
        
        private void OnSendImageOperationCompleted(object arg) {
            if ((this.SendImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendImageCompleted(this, new SendImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel GetHotel() {
            object[] results = this.Invoke("GetHotel", new object[0]);
            return ((Hotel)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelAsync() {
            this.GetHotelAsync(null);
        }
        
        /// <remarks/>
        public void GetHotelAsync(object userState) {
            if ((this.GetHotelOperationCompleted == null)) {
                this.GetHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelOperationCompleted);
            }
            this.InvokeAsync("GetHotel", new object[0], this.GetHotelOperationCompleted, userState);
        }
        
        private void OnGetHotelOperationCompleted(object arg) {
            if ((this.GetHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelCompleted(this, new GetHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rome {
        
        private Resevation[] reservationsLogField;
        
        private int idField;
        
        private int nb_badsField;
        
        private string typeField;
        
        private float priceField;
        
        private bool reservedField;
        
        private string stringImageField;
        
        /// <remarks/>
        public Resevation[] ReservationsLog {
            get {
                return this.reservationsLogField;
            }
            set {
                this.reservationsLogField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Nb_bads {
            get {
                return this.nb_badsField;
            }
            set {
                this.nb_badsField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public bool Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
        
        /// <remarks/>
        public string StringImage {
            get {
                return this.stringImageField;
            }
            set {
                this.stringImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Resevation {
        
        private int idField;
        
        private System.DateTime arrived_dateField;
        
        private System.DateTime exit_dateField;
        
        private int nb_supported_personnesField;
        
        private Client clientField;
        
        private double nb_dayField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Arrived_date {
            get {
                return this.arrived_dateField;
            }
            set {
                this.arrived_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Exit_date {
            get {
                return this.exit_dateField;
            }
            set {
                this.exit_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Nb_supported_personnes {
            get {
                return this.nb_supported_personnesField;
            }
            set {
                this.nb_supported_personnesField = value;
            }
        }
        
        /// <remarks/>
        public Client Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public double Nb_day {
            get {
                return this.nb_dayField;
            }
            set {
                this.nb_dayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Client {
        
        private string fnameField;
        
        private string lnameField;
        
        private string emailField;
        
        private string pwdField;
        
        private CreditCard cardField;
        
        /// <remarks/>
        public string Fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
            }
        }
        
        /// <remarks/>
        public CreditCard Card {
            get {
                return this.cardField;
            }
            set {
                this.cardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCard {
        
        private int idField;
        
        private string codeField;
        
        private string expiration_dateField;
        
        private int ccvField;
        
        private float soldeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_date {
            get {
                return this.expiration_dateField;
            }
            set {
                this.expiration_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Ccv {
            get {
                return this.ccvField;
            }
            set {
                this.ccvField = value;
            }
        }
        
        /// <remarks/>
        public float Solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Offre {
        
        private int idField;
        
        private int pourcentageField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Pourcentage {
            get {
                return this.pourcentageField;
            }
            set {
                this.pourcentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agence {
        
        private int idField;
        
        private string agenceNameField;
        
        private string agencPwdField;
        
        private Offre loffreField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string AgenceName {
            get {
                return this.agenceNameField;
            }
            set {
                this.agenceNameField = value;
            }
        }
        
        /// <remarks/>
        public string AgencPwd {
            get {
                return this.agencPwdField;
            }
            set {
                this.agencPwdField = value;
            }
        }
        
        /// <remarks/>
        public Offre Loffre {
            get {
                return this.loffreField;
            }
            set {
                this.loffreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Addres {
        
        private int idField;
        
        private string contryField;
        
        private string cityField;
        
        private string streetField;
        
        private string numberField;
        
        private string localityField;
        
        private string gpsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Contry {
            get {
                return this.contryField;
            }
            set {
                this.contryField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string Gps {
            get {
                return this.gpsField;
            }
            set {
                this.gpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hotel {
        
        private int idField;
        
        private string nameField;
        
        private int starField;
        
        private Rome[] roomesField;
        
        private Addres addresField;
        
        private Agence[] agencesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Star {
            get {
                return this.starField;
            }
            set {
                this.starField = value;
            }
        }
        
        /// <remarks/>
        public Rome[] Roomes {
            get {
                return this.roomesField;
            }
            set {
                this.roomesField = value;
            }
        }
        
        /// <remarks/>
        public Addres Addres {
            get {
                return this.addresField;
            }
            set {
                this.addresField = value;
            }
        }
        
        /// <remarks/>
        public Agence[] Agences {
            get {
                return this.agencesField;
            }
            set {
                this.agencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDisponibilitesCompletedEventHandler(object sender, GetDisponibilitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDisponibilitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDisponibilitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rome[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rome[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReserveRoomeCompletedEventHandler(object sender, ReserveRoomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveRoomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveRoomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Rome Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Rome)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendImageCompletedEventHandler(object sender, SendImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetHotelCompletedEventHandler(object sender, GetHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591